# Generated by Django 3.2.4 on 2021-06-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbdominalsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourstart', models.TimeField(verbose_name='Hora de Inicio')),
                ('hourend', models.TimeField(verbose_name='Hora de Fin')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('nabs', models.IntegerField(default=0, verbose_name='Cantidad de Abdominales')),
            ],
        ),
        migrations.CreateModel(
            name='WalkingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourstart', models.TimeField(verbose_name='Hora de Inicio')),
                ('hourend', models.TimeField(verbose_name='Hora de Fin')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('nabs', models.IntegerField(default=0, verbose_name='Cantidad de Pasos')),
            ],
        ),
    ]
